sequenceDiagram
    autonumber
    participant MCU as Mikrokontroler
    participant Alarm

    MCU->>MCU: Detekcija opasnosti
    MCU->>Alarm: Aktivacija alarma (zvučnog/svjetlosnog)
    Alarm-->>MCU: Potvrda aktivacije