sequenceDiagram
    autonumber
    participant MCU as Mikrokontroler

    MCU->>MCU: Analiza udaljenosti i brzine promjene
    MCU->>MCU: Utvrđivanje prijetnje
    MCU->>MCU: Spremanje rezultata za obradu