sequenceDiagram
    autonumber
    participant MCU as Mikrokontroler
    participant Komunikacija as Komunikacijski modul
    participant Server

    MCU->>Komunikacija: Priprema podataka
    Komunikacija->>Server: Slanje podataka
    Server-->>Komunikacija: Potvrda prijema
    Komunikacija-->>MCU: Potvrda slanja