sequenceDiagram
    autonumber
    participant MCU as Mikrokontroler
    participant Senzor

    MCU->>Senzor: Zahtjev za očitavanje udaljenosti
    Senzor-->>MCU: Povrat podataka o udaljenosti
    MCU->>MCU: Provjera udaljenosti (ispod sigurnosnog praga?)