sequenceDiagram
    autonumber
    participant MCU as ESP32
    participant UL as UltrazvučniSenzorLijevi
    participant UR as UltrazvučniSenzorDesni
    participant ISR as sensorWakeISR()
    participant AM as AlertManager
    participant DM as DisplayManager

    loop Radni ciklus
        MCU->>UL: trigger()
        UL-->>MCU: distanceLeft
        MCU->>UR: trigger()
        UR-->>MCU: distanceRight
        MCU->>MCU: odredi minDistance i najbliži senzor
        MCU->>AM: reset()
        alt Normalno (>=350cm)
            MCU->>AM: normalMode()
            MCU->>DM: showStatus(...)
            MCU->>DM: showSpavanje()
            MCU->>MCU: esp_deep_sleep_start()
        else Upozorenje (200–349cm)
            MCU->>AM: warningMode()
            MCU->>DM: showStatus(...)
        else Kritično (<200cm)
            MCU->>AM: criticalMode()
            MCU->>DM: showStatus(..., sensor)
        end
        
    end

    Note over MCU,ISR: Echo pin visoki signal pokreće interrupt
    ISR-->>MCU: Buđenje iz deep-sleepa