name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen documentation
        run: doxygen ./Projekt/src/Doxyfile

      # (Opcionalno) Ako želiš da se dokumentacija automatski push-a natrag:
      - name: Deploy generated docs to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Projekt/docs/html
